Workflow..

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -66,12 +66,6 @@ jobs:
         with:
           path: |
             ${{ steps.generate-keys.outputs.STORE_PATH }}
-            ${{ steps.pnpm-install.outputs.bin_dest }}
-            ${{ steps.pnpm-install.outputs.dest }}
-            ~/ratos-configuration
-            ~/klipper
-            ~/moonraker
-            **/node_modules
           key: ${{ steps.generate-keys.outputs.CACHE_KEY }}
 
       - name: Dependencies
@@ -97,88 +91,17 @@ jobs:
           repository: Arksine/moonraker
           path: "moonraker"
 
-  lint:
-    name: Lint
-    needs: [checkout_dependencies]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          repository: Rat-OS/RatOS-configurator
-          path: "ratos-configurator"
-      - uses: actions/cache/restore@v3
-        name: Restore Cache
-        with:
-          path: |
-            ${{ needs.checkout_dependencies.outputs.STORE_PATH }}
-            ${{ needs.checkout_dependencies.outputs.bin_dest }}
-            ${{ needs.checkout_dependencies.outputs.dest }}
-            ~/ratos-configuration
-            ~/klipper
-            ~/moonraker
-            **/node_modules
-          key: ${{ needs.checkout_dependencies.outputs.CACHE_KEY }}
-          restore-keys: |
-            ${{ runner.os }}-pnpm-store-
-      - name: Begin CI...
+      - name: Lint
         working-directory: ratos-configurator/src
         run: npm run lint:ci
 
-  typecheck:
-    needs: [checkout_dependencies]
-    name: Typecheck
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          repository: Rat-OS/RatOS-configurator
-          path: "ratos-configurator"
-      - uses: actions/cache/restore@v3
-        name: Restore Cache
-        with:
-          path: |
-            ${{ needs.checkout_dependencies.outputs.STORE_PATH }}
-            ${{ needs.checkout_dependencies.outputs.bin_dest }}
-            ${{ needs.checkout_dependencies.outputs.dest }}
-            ~/ratos-configuration
-            ~/klipper
-            ~/moonraker
-            **/node_modules
-          key: ${{ needs.checkout_dependencies.outputs.CACHE_KEY }}
-          restore-keys: |
-            ${{ runner.os }}-pnpm-store-
-      - name: Begin CI...
+      - name: Typecheck
         uses: fersilva16/ts-report-action@1.1.0
+        if: success() || failure() # run this step even if previous step failed
         with:
           project: ratos-configurator/src/tsconfig.json
-
-  test:
-    name: Test
-    runs-on: ubuntu-latest
-    needs: [checkout_dependencies]
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          repository: Rat-OS/RatOS-configurator
-          path: "ratos-configurator"
-      - uses: actions/cache/restore@v3
-        name: Restore Cache
-        with:
-          path: |
-            ${{ needs.checkout_dependencies.outputs.STORE_PATH }}
-            ${{ needs.checkout_dependencies.outputs.bin_dest }}
-            ${{ needs.checkout_dependencies.outputs.dest }}
-            ~/ratos-configuration
-            ~/klipper
-            ~/moonraker
-            **/node_modules
-          key: ${{ needs.checkout_dependencies.outputs.CACHE_KEY }}
-          restore-keys: |
-            ${{ runner.os }}-pnpm-store-
-      - name: Begin CI...
+          
+      - name: Run test suite
         working-directory: ratos-configurator/src
         if: success() || failure() # run this step even if previous step failed
         run: npm run test:ci --outputFile=./report.xml
